apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: db
  namespace: mesh-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          ports:
          - containerPort: 5432
            name: postgres
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
